cc.setPrompt("]##")
cc.clearResponse()
cc.cmd("ifconfig eth0 up")
//cc.cmd("udhcpc -i eth0")
cc.cmd("ifconfig eth0 192.168.99.20")
cc.cmd("insmod /ext/lib/modules/nls_utf8.ko")
cc.cmd("insmod /ext/lib/modules/cifs.ko")
cc.cmd("mount -t cifs //192.168.99.201/IPCamera/vendor /system/vendor -o username=Administrator,password=0okmnji9,sec=ntlm,iocharset=utf8")
cc.cmd("export LD_PRELOAD=/vendor/libii.so")
//cc.send("gdbserver :2222 mixer -n 1 -r 2 -v 1 -s 30 -f 30 -b 8M -o")
cc.send("mixer -n 1 -r 2 -v 1 -s 30 -f 30 -b 8M -o 2>&1 | tee /system/vendor/mixer.log")